useStackTrace: true
dcRedis:
  host: "localhost"
  port: 8803
  maxPoolInterval: 5s
  asidExp: "5m"
vault:
  host: "83.220.175.189"
  port: 8801
  clientTimeout: "10s"
  tokenRepo:
    path: "/v1/secret/data/auth-storer/tokens"
    astJwtSecretName: "astJwtSecret"
  dcRedisSecret:
    path: "/v1/secret/data/auth-storer/redis"
    dcRedisUserName: dcRedisUser
    dcRedisSecretName: dcRedisSecret
    acRedisUserName: acRedisUser
    acRedisSecretName: acRedisSecret
grpcServer:
  port: 4000
  maxPollTime: 10s